# Conan docker for HiSilicon v400 toolchain (GCC 4.8.3 glibc)
# 
#
{% set _PREFIX = 'arm-hisiv400-linux-gnueabi' %}
{% set _COMMANDs = ['addr2line'  , 'ar' , 'as' , 'c++' , 'c++filt' , 'cpp' , 'elfedit' , 
    'g++' , 'gcc' , 'gcc-4.8.3' , 'gcc-ar' , 'gcc-nm' , 'gcc-ranlib' , 'gcov' , 'gdb' , 
    'gprof' , 'ld' , 'ld.bfd' , 'nm' , 'objcopy' , 'objdump' , 'ranlib' , 'readelf' , 
    'size' , 'strings' , 'strip'] 
%}

FROM epmkit/conan-gcc8-x86:{{conan_version}}

LABEL maintainer="Mingyi Zhang <mingyi.z@outlook.com>"


ENV CC={{_PREFIX}}-gcc \
    CXX={{_PREFIX}}-g++ \
    CMAKE_C_COMPILER=arm-{{_PREFIX}}-gcc \
    CMAKE_CXX_COMPILER={{_PREFIX}}-g++ \
    STRIP={{_PREFIX}}-strip \
    RANLIB={{_PREFIX}}-gcc-ranlib\
    AS=arm-{{_PREFIX}}-as \
    AR=arm-{{_PREFIX}}-ar \
    LD=arm-{{_PREFIX}}-ld

RUN cd /opt \
    && sudo wget {{config['tarball']['arm-hisiv400-linux']}} \
    && sudo tar -xvzf arm-hisiv400-linux.tar.gz \
    && sudo chown -R conan:1001 /opt/arm-hisiv400-linux \
    && sudo rm /opt/arm-hisiv400-linux.tar.gz \
    {% for i in _COMMANDs -%}
    && sudo update-alternatives --install /usr/bin/{{_PREFIX}}-{{i}} \
                                          {{_PREFIX}}-{{i}} \
                                          /opt/arm-hisiv400-linux/bin/{{_PREFIX}}-{{i}} 100 \
    {% endfor -%}
    && conan profile new default --detect \
    && conan profile update settings.arch=armv7 default
